### ISSUE TITLE
linux error

### ISSUE THREAD

**Issue by carlosnewmusic** [thometal/zpaqgui#3]
!SESSION 2018-04-28 23:57:38.906 -----------------------------------------------
eclipse.buildId=unknown
java.version=10.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=es_ES
Framework arguments:  -clearPersistedState
Command-line arguments:  -os linux -ws gtk -arch x86_64 -clearPersistedState

!ENTRY org.eclipse.equinox.app 0 0 2018-04-28 23:57:42.568
!MESSAGE Product de.tt.zpaqgui.product could not be found.

!ENTRY de.tt.zpaqgui 2 0 2018-04-28 23:57:43.737
!MESSAGE Could not resolve module: de.tt.zpaqgui [2]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"

!ENTRY org.eclipse.osgi 4 0 2018-04-28 23:57:43.737
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.AssertionFailedException: null argument:applicationXMI argument missing
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:85)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:373)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:146)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by thometal** [comment]
currently only java version 8.* is supported as java runtime. You are running version 10.0.1.

**Comment by carlosnewmusic** [comment]
and do not plan to update and document it? so that any other person can continue with the development of the graphical interface
